# Production Alerting Rules for Scholarship Discovery API
# Prometheus AlertManager Configuration

groups:
- name: scholarship-api-critical
  rules:
  - alert: HighLatencyP95
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="scholarship-api",endpoint!~"/docs|/metrics"}[5m])) > 0.12
    for: 10m
    labels:
      severity: critical
      service: scholarship-api
    annotations:
      summary: "High P95 latency detected"
      description: "P95 latency is {{ $value }}s, above 120ms threshold for 10 minutes"
      runbook_url: "https://docs.company.com/runbooks/high-latency"

  - alert: HighErrorRate
    expr: rate(http_requests_total{job="scholarship-api",status=~"5..",endpoint!~"/docs|/metrics"}[5m]) / rate(http_requests_total{job="scholarship-api",endpoint!~"/docs|/metrics"}[5m]) > 0.001
    for: 5m
    labels:
      severity: critical
      service: scholarship-api
    annotations:
      summary: "High 5xx error rate detected"
      description: "5xx error rate is {{ $value | humanizePercentage }}, above 0.1% threshold"
      runbook_url: "https://docs.company.com/runbooks/high-error-rate"

  - alert: DatabaseConnectionPoolHigh
    expr: postgres_connections_active{job="scholarship-api"} / postgres_connections_max{job="scholarship-api"} > 0.8
    for: 5m
    labels:
      severity: warning
      service: scholarship-api
    annotations:
      summary: "Database connection pool utilization high"
      description: "Connection pool is {{ $value | humanizePercentage }} utilized"
      runbook_url: "https://docs.company.com/runbooks/db-connections"

  - alert: AgentTaskFailureRate
    expr: rate(agent_tasks_failed_total{job="scholarship-api"}[5m]) / rate(agent_tasks_total{job="scholarship-api"}[5m]) > 0.02
    for: 10m
    labels:
      severity: warning
      service: scholarship-api
    annotations:
      summary: "Agent task failure rate high"
      description: "Agent task failure rate is {{ $value | humanizePercentage }}, above 2% threshold"

  - alert: OpenAIServiceDegraded
    expr: rate(openai_requests_failed_total{job="scholarship-api"}[5m]) / rate(openai_requests_total{job="scholarship-api"}[5m]) > 0.05
    for: 5m
    labels:
      severity: warning
      service: scholarship-api
    annotations:
      summary: "OpenAI service failure rate high"
      description: "OpenAI failure rate is {{ $value | humanizePercentage }}, above 5% threshold"

  - alert: ServiceDown
    expr: up{job="scholarship-api"} == 0
    for: 1m
    labels:
      severity: critical
      service: scholarship-api
    annotations:
      summary: "Scholarship API service is down"
      description: "Service has been down for more than 1 minute"
      runbook_url: "https://docs.company.com/runbooks/service-down"

- name: scholarship-api-performance
  rules:
  - alert: HighMemoryUsage
    expr: container_memory_usage_bytes{pod=~"scholarship-api-.*"} / container_spec_memory_limit_bytes{pod=~"scholarship-api-.*"} > 0.85
    for: 10m
    labels:
      severity: warning
      service: scholarship-api
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is {{ $value | humanizePercentage }} of limit"

  - alert: HighCPUUsage
    expr: rate(container_cpu_usage_seconds_total{pod=~"scholarship-api-.*"}[5m]) > 0.8
    for: 10m
    labels:
      severity: warning
      service: scholarship-api
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is {{ $value | humanizePercentage }}"

  - alert: RedisHitRateLow
    expr: redis_keyspace_hits_total{job="scholarship-api"} / (redis_keyspace_hits_total{job="scholarship-api"} + redis_keyspace_misses_total{job="scholarship-api"}) < 0.85
    for: 10m
    labels:
      severity: warning
      service: scholarship-api
    annotations:
      summary: "Redis cache hit rate low"
      description: "Cache hit rate is {{ $value | humanizePercentage }}, below 85% threshold"

- name: scholarship-api-security
  rules:
  - alert: HighAuthFailureRate
    expr: rate(http_requests_total{job="scholarship-api",status="401"}[5m]) > 0.08
    for: 5m
    labels:
      severity: warning
      service: scholarship-api
    annotations:
      summary: "High authentication failure rate"
      description: "Authentication failures: {{ $value }} per second"

  - alert: RateLimitingTriggered
    expr: (rate(http_requests_total{job="scholarship-api",status="429"}[5m]) / rate(http_requests_total{job="scholarship-api"}[5m])) > 0.01
    for: 5m
    labels:
      severity: info
      service: scholarship-api
    annotations:
      summary: "Rate limiting frequently triggered"
      description: "Rate limit triggers: {{ $value }} per second"

- name: scholarship-api-slo-burn
  rules:
  # TRUE ERROR BUDGET BURN-RATE ALERTS
  # SLOs: 99.9% availability, P95 ≤120ms (5% error budget), <0.1% 5xx errors
  
  # === LATENCY BURN-RATE ALERTS ===
  # SLO: P95 ≤120ms means 5% of requests may exceed 120ms (5% error budget)
  # Calculate actual burn rate: (1 - compliance_rate) vs error budget × multiplier
  - alert: SLOLatencyBurnFast
    expr: |
      (
        (
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="scholarship-api",endpoint!~"/docs|/metrics",le="0.12"}[1h])) by (service)
            / 
            sum(rate(http_request_duration_seconds_count{job="scholarship-api",endpoint!~"/docs|/metrics"}[1h])) by (service)
          )
        ) > (14.4 * 0.05)
        and
        (
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="scholarship-api",endpoint!~"/docs|/metrics",le="0.12"}[6h])) by (service)
            / 
            sum(rate(http_request_duration_seconds_count{job="scholarship-api",endpoint!~"/docs|/metrics"}[6h])) by (service)
          )
        ) > (6 * 0.05)
      )
    for: 2m
    labels:
      severity: critical
      service: scholarship-api
      burn_rate: fast
      slo_type: latency
    annotations:
      summary: "Fast latency SLO burn - consuming error budget rapidly"
      description: "Latency budget burn rate {{ $value | humanizePercentage }} exceeds fast burn threshold (72% for 1h, 30% for 6h). Consuming 30-day error budget in ~2 days."
      runbook_url: "https://docs.company.com/runbooks/slo-latency-burn"
      
  - alert: SLOLatencyBurnSlow
    expr: |
      (
        (
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="scholarship-api",endpoint!~"/docs|/metrics",le="0.12"}[6h])) by (service)
            / 
            sum(rate(http_request_duration_seconds_count{job="scholarship-api",endpoint!~"/docs|/metrics"}[6h])) by (service)
          )
        ) > (6 * 0.05)
        and
        (
          1 - (
            sum(rate(http_request_duration_seconds_bucket{job="scholarship-api",endpoint!~"/docs|/metrics",le="0.12"}[24h])) by (service)
            / 
            sum(rate(http_request_duration_seconds_count{job="scholarship-api",endpoint!~"/docs|/metrics"}[24h])) by (service)
          )
        ) > (3 * 0.05)
      )
    for: 15m
    labels:
      severity: warning
      service: scholarship-api
      burn_rate: slow
      slo_type: latency
    annotations:
      summary: "Slow latency SLO burn - sustained error budget consumption"
      description: "Latency budget burn rate {{ $value | humanizePercentage }} exceeds slow burn threshold (30% for 6h, 15% for 24h). Consuming 30-day error budget in ~10 days."
      runbook_url: "https://docs.company.com/runbooks/slo-latency-burn"

  # === ERROR RATE BURN-RATE ALERTS ===
  # SLO: <0.1% 5xx errors (0.001 as decimal)
  # Calculate actual 5xx rate and burn rate relative to SLO
  - alert: SLOErrorRateBurnFast
    expr: |
      (
        (
          sum(rate(http_requests_total{job="scholarship-api",status=~"5..",endpoint!~"/docs|/metrics"}[1h])) by (service)
          / 
          sum(rate(http_requests_total{job="scholarship-api",endpoint!~"/docs|/metrics"}[1h])) by (service)
        ) > (14.4 * 0.001)
        and
        (
          sum(rate(http_requests_total{job="scholarship-api",status=~"5..",endpoint!~"/docs|/metrics"}[6h])) by (service)
          / 
          sum(rate(http_requests_total{job="scholarship-api",endpoint!~"/docs|/metrics"}[6h])) by (service)
        ) > (6 * 0.001)
      )
    for: 2m
    labels:
      severity: critical
      service: scholarship-api
      burn_rate: fast
      slo_type: error_rate
    annotations:
      summary: "Fast error rate SLO burn - consuming error budget rapidly"
      description: "5xx error rate {{ $value | humanizePercentage }} exceeds fast burn threshold (1.44% for 1h window). Consuming 30-day error budget in ~2 days."
      runbook_url: "https://docs.company.com/runbooks/slo-error-burn"
      
  - alert: SLOErrorRateBurnSlow
    expr: |
      (
        (
          sum(rate(http_requests_total{job="scholarship-api",status=~"5..",endpoint!~"/docs|/metrics"}[6h])) by (service)
          / 
          sum(rate(http_requests_total{job="scholarship-api",endpoint!~"/docs|/metrics"}[6h])) by (service)
        ) > (6 * 0.001)
        and
        (
          sum(rate(http_requests_total{job="scholarship-api",status=~"5..",endpoint!~"/docs|/metrics"}[24h])) by (service)
          / 
          sum(rate(http_requests_total{job="scholarship-api",endpoint!~"/docs|/metrics"}[24h])) by (service)
        ) > (3 * 0.001)
      )
    for: 15m
    labels:
      severity: warning
      service: scholarship-api
      burn_rate: slow
      slo_type: error_rate
    annotations:
      summary: "Slow error rate SLO burn - sustained error budget consumption"
      description: "5xx error rate {{ $value | humanizePercentage }} exceeds slow burn threshold (0.6% for 6h, 0.3% for 24h). Consuming 30-day error budget in ~10 days."
      runbook_url: "https://docs.company.com/runbooks/slo-error-burn"

  # === AVAILABILITY BURN-RATE ALERTS ===
  # SLO: 99.9% availability (0.1% downtime allowed = 43.8 min/30 days)
  # Calculate actual downtime burn rate against error budget
  - alert: SLOAvailabilityBurnFast
    expr: |
      (
        (
          (1 - avg_over_time(up{job="scholarship-api"}[1h])) > (14.4 * 0.001)
        )
        and
        (
          (1 - avg_over_time(up{job="scholarship-api"}[6h])) > (6 * 0.001)
        )
      )
    for: 2m
    labels:
      severity: critical
      service: scholarship-api
      burn_rate: fast
      slo_type: availability
    annotations:
      summary: "Fast availability SLO burn - consuming error budget rapidly"
      description: "Downtime rate {{ $value | humanizePercentage }} exceeds fast burn threshold (1.44% for 1h). Consuming 30-day error budget in ~2 days."
      runbook_url: "https://docs.company.com/runbooks/slo-availability-burn"
      
  - alert: SLOAvailabilityBurnSlow
    expr: |
      (
        (
          (1 - avg_over_time(up{job="scholarship-api"}[6h])) > (6 * 0.001)
        )
        and
        (
          (1 - avg_over_time(up{job="scholarship-api"}[24h])) > (3 * 0.001)
        )
      )
    for: 15m
    labels:
      severity: warning
      service: scholarship-api
      burn_rate: slow
      slo_type: availability
    annotations:
      summary: "Slow availability SLO burn - sustained error budget consumption"
      description: "Downtime rate {{ $value | humanizePercentage }} exceeds slow burn threshold (0.6% for 6h, 0.3% for 24h). Consuming 30-day error budget in ~10 days."
      runbook_url: "https://docs.company.com/runbooks/slo-availability-burn"

- name: scholarship-api-business
  rules:
  - alert: SearchRequestsDropped
    expr: rate(search_requests_total{job="scholarship-api"}[1h]) < rate(search_requests_total{job="scholarship-api"}[1h] offset 1h) * 0.5
    for: 30m
    labels:
      severity: warning
      service: scholarship-api
    annotations:
      summary: "Search request volume dropped significantly"
      description: "Search requests down {{ $value | humanizePercentage }} from previous hour"

  - alert: EligibilityCheckErrors
    expr: rate(eligibility_check_errors_total{job="scholarship-api"}[5m]) > 0.02
    for: 10m
    labels:
      severity: warning
      service: scholarship-api
    annotations:
      summary: "Eligibility check error rate high"
      description: "Eligibility check errors: {{ $value }} per second"