"""
Report Branding Utility for Scholar AI Advisor

Per Unified Business + Legal Pages specification, all reports must include
a footer with app branding, company information, and contact details.
"""

from datetime import datetime

BRAND_NAME = "Scholar AI Advisor"
COMPANY_LEGAL_NAME = "Referral Service LLC"
MAIN_SITE_URL = "https://scholaraiadvisor.com"
CONTACT_EMAIL = "support@referralsvc.com"
CONTACT_PHONE = "602-796-0177"
CONTACT_ADDRESS = "16031 N 171st Ln, Surprise, AZ 85388, USA"
COPYRIGHT_LINE = "© 2025 Referral Service LLC. All rights reserved."

APP_NAME = "scholarship_api"
APP_BASE_URL = "https://scholarship-api-jamarrlmayes.replit.app"


def get_report_footer() -> str:
    """
    Returns the standard report footer text for all generated reports.
    Use this in plain text reports, PDFs, emails, and terminal output.
    """
    return f"This report was generated by {APP_NAME} — {APP_BASE_URL} | {BRAND_NAME} by {COMPANY_LEGAL_NAME} | {CONTACT_EMAIL} | {CONTACT_PHONE}"


def get_report_footer_html() -> str:
    """
    Returns HTML-formatted report footer for web reports.
    Font size 10-11px, high contrast, accessible.
    """
    return f'''<div style="margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; font-size: 10px; color: #64748b; text-align: center; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
    This report was generated by <strong>{APP_NAME}</strong> — <a href="{APP_BASE_URL}" style="color: #0066cc;">{APP_BASE_URL}</a> | 
    {BRAND_NAME} by {COMPANY_LEGAL_NAME} | 
    <a href="mailto:{CONTACT_EMAIL}" style="color: #0066cc;">{CONTACT_EMAIL}</a> | 
    <a href="tel:{CONTACT_PHONE}" style="color: #0066cc;">{CONTACT_PHONE}</a>
</div>'''


def get_report_footer_dict() -> dict:
    """
    Returns report footer as a dictionary for JSON responses.
    Include this in API responses that return report data.
    """
    return {
        "report_metadata": {
            "generated_by": APP_NAME,
            "app_base_url": APP_BASE_URL,
            "brand_name": BRAND_NAME,
            "company_legal_name": COMPANY_LEGAL_NAME,
            "contact_email": CONTACT_EMAIL,
            "contact_phone": CONTACT_PHONE,
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "copyright": COPYRIGHT_LINE
        }
    }


def get_report_header_dict() -> dict:
    """
    Returns report header as a dictionary for API responses.
    Use at the top level of JSON report responses.
    """
    return {
        "brand": BRAND_NAME,
        "company": COMPANY_LEGAL_NAME,
        "app": {
            "name": APP_NAME,
            "base_url": APP_BASE_URL
        },
        "contact": {
            "email": CONTACT_EMAIL,
            "phone": CONTACT_PHONE,
            "address": CONTACT_ADDRESS,
            "website": MAIN_SITE_URL
        }
    }


def add_report_branding(data: dict) -> dict:
    """
    Adds report branding to an existing dictionary response.
    Places metadata at the root level of the response.
    
    Usage:
        return add_report_branding({
            "results": [...],
            "summary": {...}
        })
    """
    branded = dict(data)
    branded["_report"] = get_report_footer_dict()["report_metadata"]
    return branded


LEGAL_LINKS = {
    "privacy_policy": f"{APP_BASE_URL}/privacy",
    "terms_of_service": f"{APP_BASE_URL}/terms",
    "accessibility": f"{APP_BASE_URL}/accessibility"
}


COMPANY_INFO = {
    "brand_name": BRAND_NAME,
    "company_legal_name": COMPANY_LEGAL_NAME,
    "main_site_url": MAIN_SITE_URL,
    "contact_email": CONTACT_EMAIL,
    "contact_phone": CONTACT_PHONE,
    "contact_address": CONTACT_ADDRESS,
    "copyright_line": COPYRIGHT_LINE,
    "app_name": APP_NAME,
    "app_base_url": APP_BASE_URL,
    "legal_links": LEGAL_LINKS
}
